default_config:

config:

homeassistant:
  time_zone: Europe/London

alarm_control_panel: !include alarm.yaml

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate
system_health:   

influxdb:
  host: !secret influx_host
  port: 8086
  database: homeassistant
  username: !secret influx_username
  password: !secret influx_password
  max_retries: 3
  default_measurement: state
  tags_attributes:
    - friendly_name
    - hidden
  exclude:
    domains:
      - automation
      - group  
  
prometheus:
  filter:
#    include_domains:
#      - alarm_control_panel
#      - light
    include_entity_globs:
      - sensor.weather_*
      - light.light_*
      - binary_sensor.magnet_*
      - switch.plug_*
      - sensor.valetudo_robot_current_*
      - sensor.valetudo_robot_main_*
      - sensor.steam_*
#    exclude_entities:
      - light.kitchen_light

#recorder:
#  db_url: !secret db_url
  
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
switch: !include switches.yaml
#zha_map:
#zwave:
#  usb_path: /dev/ttyACM1
#  device_config: !include zwave_device_config.yaml

media_player:
  - platform: samsungtv_tizen
    host: !secret samsungtv_ip
    mac: !secret samsungtv_mac
    port: 8002
    source_list: '{"Sleep Timer": "KEY_SLEEP", "PlayStation": "KEY_HDMI1", "PC": "KEY_HDMI2", "Switch": "KEY_HDMI3"}'
    app_list: '{"YouTube": "111299001912", "Netflix": "11101200001", "Plex": "3201512006963", "Prime Video": "3201512006785", "Iplayer": "3201507004202"}'
#    protocol: ws
#    timeout: 25

cloud:
wake_on_lan:
discovery:
#  ignore:
#    - igd
frontend:
  themes: !include_dir_merge_named themes

#Device tracking - Configure in Configuration menu, only Chris tracked
device_tracker:

#Logging
logger: !include logging.yaml

input_select:

  themes:
    name: 'Themes'
    icon: mdi:format-paint
    options:
      - Caule Black Rose
      - Caule Black Purple
      - Caule Black Blue 
      - Caule Black Aqua
      - Caule Black Green
      - Caule Black Yellow
      - Caule Black Orange
      - Caule Black Coral
      - Caule Black Pink
      - Caule Black Gray
      - Caule Dark Rose
      - Caule Dark Purple
      - Caule Dark Blue 
      - Caule Dark Aqua
      - Caule Dark Green
      - Caule Dark Yellow
      - Caule Dark Orange
      - Caule Dark Coral
      - Caule Dark Pink
      - Caule Dark Gray
      - Caule Light Rose
      - Caule Light Purple
      - Caule Light Blue 
      - Caule Light Aqua
      - Caule Light Green
      - Caule Light Yellow
      - Caule Light Orange
      - Caule Light Coral
      - Caule Light Pink
      - Caule Light Gray
      - Caule Black Rose Glass
      - Caule Black Purple Glass
      - Caule Black Blue Glass 
      - Caule Black Aqua Glass
      - Caule Black Green Glass
      - Caule Black Yellow Glass
      - Caule Black Orange Glass
      - Caule Black Coral Glass
      - Caule Black Pink Glass
      - Caule Black Gray Glass      
      - Default
